### ISSUE TITLE
ChromeDriver is not working with selenium 2.45.0?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [FuckTheWorld/chromedriver#1045]
```
Hi, 

I tried to run tests in chrome driver using below code. I am using maven.

    <dependency>
                <groupId>org.seleniumhq.selenium</groupId>
                <artifactId>selenium-java</artifactId>
                <version>2.45.0</version>
            </dependency>
            <dependency>
                <groupId>org.seleniumhq.selenium</groupId>
                <artifactId>selenium-server</artifactId>
                <version>2.45.0</version>
            </dependency>

------
    public WebDriver startChromeDriver(WebDriver driver, File file) {
        file = new File("F:\\work\\chromedriver\\chromedriver.exe");
        System.setProperty("webdriver.chrome.driver", file.getAbsolutePath());
        driver = new ChromeDriver();
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);

        return driver;
    }

public void test(){
driver.get("http://google.com")
}
------
I am getting this error 

java.lang.NoClassDefFoundError: 
org/openqa/selenium/remote/service/DriverService$Builder
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:82)
    at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:117)

```

Original issue reported on code.google.com by `rajeev...@gmail.com` on 2 Mar 2015 at 6:39

**Comment by ravitejanemana** [comment]
Hi guys...I have a issue here..I am getting chromedriver.exe has stopped error. and the below is the console. Could you plase let me know what to do in this case.

[INFO] [BaseTest] [startWebDriverClient] startWebDriverClient - Starting remoteWebDriver for URL http://localhost:4433/wd/hub 
 [INFO] [WebDriverFactory] [getWebdriver] Browser type is:chrome 
 [ERROR] [BaseTest] [startWebDriverClient] Could not start a new session. Possible causes are : 
	 1. Selenium Grid is not proprly set up
	 2. Drivers are not properly added to the path 
	 3. Port mentioned in the Grid properties file is different from port in which Remote server has started 
 org.openqa.selenium.WebDriverException: Connection reset
Command duration or timeout: 55.64 seconds
Build info: version: '2.41.0', revision: '3192d8a6c4449dc285928ba024779344f5423c58', time: '2014-03-27 11:29:39'
System info: host: '01HW475612', ip: '172.25.54.21', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_72'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
	at com.tcs.saf.base.BaseTest.startWebDriverClient(BaseTest.java:354)
	at com.tcs.saf.base.BaseTest.beforemethod(BaseTest.java:158)
